image: python:3.7-alpine

test:
  stage: test
  script:
  - apk update && apk add build-base \
      && apk add -u libgcc libquadmath musl \
      && apk add -u libgfortran \
      && apk add -u lapack-dev
  - pip install -r requirements.txt
  - pip install -U sphinx sphinx_rtd_theme recommonmark
  - sphinx-build -b html -a ./docs/source public
  only:
  - branches
  except:
  - master

pages:
  stage: deploy
  script:
  - apk update && apk add build-base \
      && apk add -u libgcc libquadmath musl \
      && apk add -u libgfortran \
      && apk add -u lapack-dev
  - pip install -r requirements.txt
  - pip install -U sphinx sphinx_rtd_theme recommonmark
  - sphinx-build -b html -a ./docs/source public
  artifacts:
    paths:
    - public
  only:
  - master
